### ISSUE TITLE
Cron dosn't work properly with Rust(?).

### ISSUE THREAD

**Issue by ryrzy** [OpenGamePanel/Module-Cron#13] opened 2017-11-26 08:44 UTC
hi,
cron module is not working properly with Rust (dont know other games),
like i have writen on forum: https://www.opengamepanel.org/forum/viewthread.php?thread_id=4137&rowstart=200&showlast=true#post_30096
cron dosn't add environment variable needed to start the server in start script, manual start has this line:

export LD_LIBRARY_PATH="/home/ogp_agent/OGP_User_Files/xx/RustDedicated_Data/Plugins/x86_64"

crontab script dosn't :)

**Comment by Zorrototo** [comment] 2017-11-27 10:15
To be clear, the startup script generated by Cron module does not contain the environment variable so the games requiring that are not properly starting or restarting with the Cron module, when it works as intended when you manually start or restart from Panel. Cron module never got updated when the environment variable where added to XML files.

**Comment by Zorrototo** [comment] 2017-11-28 00:31
Update Panel and Cron module. It should be solved now.

edit: now I'm thinking about it, I'm not even sure it wouldn't need an Agent update too for the Cron Module to be fixed for this issue.. anyway, try to update everything and see if that is working now.

**Comment by own3mall** [comment] 2017-11-28 00:49
It will soon... this is not completed yet.

**Comment by Zorrototo** [comment] 2017-11-28 00:50
Yep I just though about it when reviewing the changes.

**Comment by own3mall** [comment] 2017-11-28 00:53
Now it should be fixed.  Please update web panel files, and then update Cron Module.  

You will need to click on the "Edit" button without making any changes to each existing cronjob in order for them to update to the new format.  

That, or you need to delete each existing cronjob and recreate them before this will work.

**Comment by ryrzy** [comment] 2017-11-28 06:42
it looks like now is ok :) thank you all for help :)

**Comment by rocco27** [comment] 2017-12-03 11:59
Happy end, report can be closed now. Thanks!

**Closed as completed by rocco27** 2017-12-03 11:59 UTC
